% script to pre-process .SAC binary files for cross-correlated waveforms 
% the negative and positive lag correlations are separated and stacked 
% output appropriate for multiple frequency analysis 
% (i.e., Computer Programs in Seismology, $ do_mft sac_file_name.sac)
% Dependencies: sac2mat = converts .sac files to matlab-speak
%               mksac = translates processed waveform to 
% Author: Marlon D. Ramos
% x-corr = cross correlation 
clc
clear; 

% I presume that your working directory contains the .SAC files to be analyzed... 
% I furthermore presume that one is working in a linux/unix OS
! ls *.SAC > sac_files.txt

fileID=fopen('sac_files.txt', 'r'); 
files2process=textscan(fileID,'%s');

allFiles=files2process{1};
[Nfiles,~]=size(allFiles); 

for ii = 1:Nfiles
    % read in .sac file 
    fileIn=allFiles{ii};
    % [data, npts, stat, delta, station, KCMPNM,KNETWK, KUSER0, KUSER1] = sac2mat(fileIn); 
    data=rdsac(fileIn); 
    % cut waveforms at 0 time and separate negative from positive x-corr
    % nmax=round(npts/2); 
    nmax=(data.HEADER.NPTS)/2; 
    % negative x-corr
    data_neg=data.d(1:nmax); 
    data_neg=flipud(data_neg);   % reverse dir
    % posative x-corr
    data_pos=data.d(nmax:end-1); 
    % stacked x-corr
    data_stack=data_pos + data_neg; 
    NPTS=numel(data_stack); 
    
    %- write out new .sac file----
    fileOut=strcat(fileIn,'.sum'); 
    'writing out ' 
    fileOut
    % USER1=MIN period used for do_mft analysis - must set manually 
    % USER2=MAX period used for do_mft analysis - must set manually 
    mksac(fileOut,data_stack,now,'DELTA',data.HEADER.DELTA,...
        'DEPMIN', data.HEADER.DEPMIN, 'DEPMAX', data.HEADER.DEPMAX, ...
        'SCALE', data.HEADER.SCALE, 'B', 0.0e+1, 'E', NPTS, ...
        'STLA',data.HEADER.STLA, 'STLO',data.HEADER.STLO, ...
         'STEL',data.HEADER.STEL, ...
         'STDP', data.HEADER.STDP, 'EVLA', data.HEADER.EVLA,  ...
         'EVEL', data.HEADER.EVEL,'EVLO', data.HEADER.EVLO, ...
         'USER1', 0.0e0, 'USER2', 2.00e+2, ...
         'DEPMIN', data.HEADER.DEPMEN, ...
         'CMPAZ', data.HEADER.CMPAZ, 'CMPINC', data.HEADER.CMPINC, ...
         'NZYEAR', data.HEADER.NZYEAR, 'NZJDAY', data.HEADER.NZJDAY, ...
         'NZHOUR', data.HEADER.NZHOUR, 'NZMIN', data.HEADER.NZMIN, ...
         'NZSEC', data.HEADER.NZSEC,'NZMSEC', data.HEADER.NZMSEC,...
         'NVHDR', data.HEADER.NVHDR, 'NORID', data.HEADER.NORID, ...
         'NEVID', data.HEADER.NEVID, 'NPTS', NPTS, ...
         'IFTYPE', data.HEADER.IFTYPE, 'LEVEN', data.HEADER.LEVEN, ... 
         'LPSPOL', data.HEADER.LPSPOL, 'LCALDA', data.HEADER.LCALDA, ...
         'KSTNM', data.HEADER.KSTNM, 'KHOLE', data.HEADER.KHOLE,... 
         'KUSER0', data.HEADER.KUSER0, 'KUSER1', data.HEADER.KUSER1, ...
         'LOVROK', true,...
         'KCMPNM',data.HEADER.KCMPNM , 'KNETWK', data.HEADER.KNETWK , ...
         'NZDTTM', data.HEADER.NZDTTM, 'KZDATE', data.HEADER.KZDATE, 'KZTIME',data.HEADER.KZTIME)
    
end 